import React, { useEffect, useState } from "react";
import DashboardLayout from "../layout/DashboardLayout";
import "./Reports.css";
import jsPDF from "jspdf";
import "jspdf-autotable";


export default function Reports() {
  const [data, setData] = useState([]);
  const [summary, setSummary] = useState(null);

  useEffect(() => {
    try {
      const d = JSON.parse(localStorage.getItem("uploadedData")) || [];
      const s = JSON.parse(localStorage.getItem("uploadedSummary")) || null;
      setData(d);
      setSummary(s);
    } catch (e) {
      console.error("Failed to read stored data", e);
    }
  }, []);

  const downloadCSV = () => {
    if (!data || data.length === 0) return alert("No data to export.");

    const headers = Object.keys(data[0]).join(",");
    const rows = data.map(row => Object.values(row).join(",")).join("\n");

    const blob = new Blob([headers + "\n" + rows], { type: "text/csv" });
    const url = URL.createObjectURL(blob);

    const a = document.createElement("a");
    a.href = url;
    a.download = "Report.csv";
    a.click();
  };

  const downloadPDF = () => {
  if (!data || data.length === 0) {
    alert("No data to export");
    return;
  }

  const doc = new jsPDF();

  // Title
  doc.setFontSize(18);
  doc.text("Analytics Pro - Data Report", 14, 20);

  // Summary Section
  doc.setFontSize(12);
  doc.text("Summary:", 14, 35);

  const summaryData = [
    ["Total Rows", summary?.rows || 0],
    ["Total Columns", summary?.columns || 0]
  ];

  doc.autoTable({
    startY: 40,
    head: [["Metric", "Value"]],
    body: summaryData,
  });

  // Sample Data Table
  doc.text("Sample Data:", 14, doc.lastAutoTable.finalY + 15);

  const columns = Object.keys(data[0]);
  const sampleRows = data.slice(0, 10).map(row => Object.values(row));

  doc.autoTable({
    startY: doc.lastAutoTable.finalY + 20,
    head: [columns],
    body: sampleRows,
  });

  // Footer
  doc.text(
    "Generated by Analytics Pro Dashboard",
    14,
    doc.internal.pageSize.height - 10
  );

  doc.save("Report.pdf");
};

  return (
    <DashboardLayout>
      <div className="reports-container">

        <h2 className="report-title">Dataset Report</h2>
        <p className="report-sub">Automatically generated summary & analytics</p>

        {/* Summary Section */}
        <div className="summary-box">
          <h3>Summary</h3>
          {summary ? (
            <ul>
              <li><strong>Total Rows:</strong> {summary.rows}</li>
              <li><strong>Total Columns:</strong> {summary.columns}</li>
            </ul>
          ) : (
            <p>No summary available. Upload data first.</p>
          )}
        </div>

        {/* Sample Data */}
        <div className="sample-box">
          <h3>Sample Data</h3>
          {data.length > 0 ? (
            <table className="report-table">
              <thead>
                <tr>
                  {Object.keys(data[0]).map((key) => (
                    <th key={key}>{key}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {data.slice(0, 5).map((row, i) => (
                  <tr key={i}>
                    {Object.values(row).map((val, j) => (
                      <td key={j}>{val}</td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          ) : (
            <p>No data found.</p>
          )}
        </div>

        {/* Charts Notice */}
        <div className="chart-info">
          <p>Charts generated on Dashboard & Tools pages will be included in PDF export.</p>
        </div>

        {/* Buttons */}
        <div className="btn-row">
          <button className="btn btn-success" onClick={downloadCSV}>Download CSV</button>
          <button className="btn btn-danger" onClick={downloadPDF}>Download PDF</button>
        </div>

      </div>
    </DashboardLayout>
  );
}
