import React, { useEffect, useState, useRef } from "react";
import jsPDF from "jspdf";
import "jspdf-autotable";
import { gsap } from "gsap";
import { MdAssessment, MdDownload, MdPictureAsPdf, MdInfo, MdTableView } from "react-icons/md";

export default function Reports() {
  const [data, setData] = useState([]);
  const [summary, setSummary] = useState(null);
  const pageRef = useRef(null);

  useEffect(() => {
    try {
      const d = JSON.parse(localStorage.getItem("uploadedData")) || [];
      const s = JSON.parse(localStorage.getItem("uploadedSummary")) || null;
      setData(d);
      setSummary(s);
    } catch (e) {
      console.error("Failed to read stored data", e);
    }
  }, []);

  useEffect(() => {
    const ctx = gsap.context(() => {
      gsap.from(".report-anim", {
        y: 30,
        opacity: 0,
        duration: 0.6,
        stagger: 0.1,
        ease: "power2.out",
      });
    }, pageRef);
    return () => ctx.revert();
  }, []);

  const downloadCSV = () => {
    if (!data || data.length === 0) return alert("No data to export.");
    const headers = Object.keys(data[0]).join(",");
    const rows = data.map((row) => Object.values(row).join(",")).join("\n");
    const blob = new Blob([headers + "\n" + rows], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "Report.csv";
    a.click();
  };

  const downloadPDF = () => {
    if (!data || data.length === 0) return alert("No data to export");
    const doc = new jsPDF();
    doc.setFontSize(18);
    doc.text("Analytics Pro - Data Report", 14, 20);
    doc.setFontSize(12);
    doc.text("Summary:", 14, 35);
    const summaryData = [
      ["Total Rows", summary?.rows || 0],
      ["Total Columns", summary?.columns || 0],
    ];
    doc.autoTable({ startY: 40, head: [["Metric", "Value"]], body: summaryData });
    doc.text("Sample Data:", 14, doc.lastAutoTable.finalY + 15);
    const columns = Object.keys(data[0]);
    const sampleRows = data.slice(0, 10).map((row) => Object.values(row));
    doc.autoTable({ startY: doc.lastAutoTable.finalY + 20, head: [columns], body: sampleRows });
    doc.text("Generated by Analytics Pro Dashboard", 14, doc.internal.pageSize.height - 10);
    doc.save("Report.pdf");
  };

  return (
      <div ref={pageRef}>
        {/* Header */}
        <div className="report-anim mb-6">
          <h2 className="text-2xl md:text-3xl font-bold text-slate-800 dark:text-white tracking-tight flex items-center gap-2">
            <MdAssessment className="text-indigo-500" /> Reports
          </h2>
          <p className="text-slate-500 dark:text-slate-400 mt-1">
            Automatically generated summary & analytics
          </p>
        </div>

        {/* Summary */}
        <div className="report-anim bg-white dark:bg-slate-800/50 rounded-2xl border border-slate-200 dark:border-slate-700/50 p-5 shadow-sm mb-6">
          <h3 className="text-base font-semibold text-slate-800 dark:text-slate-200 mb-3">Summary</h3>
          {summary ? (
            <div className="grid grid-cols-2 gap-4">
              <div className="p-4 rounded-xl bg-linear-to-br from-indigo-50 to-indigo-100/50 dark:from-indigo-500/10 dark:to-indigo-500/5 border border-indigo-100 dark:border-indigo-500/20">
                <p className="text-xs text-indigo-500 uppercase tracking-wider font-medium mb-1">Total Rows</p>
                <p className="text-2xl font-bold text-indigo-700 dark:text-indigo-300">{summary.rows}</p>
              </div>
              <div className="p-4 rounded-xl bg-linear-to-br from-emerald-50 to-emerald-100/50 dark:from-emerald-500/10 dark:to-emerald-500/5 border border-emerald-100 dark:border-emerald-500/20">
                <p className="text-xs text-emerald-500 uppercase tracking-wider font-medium mb-1">Total Columns</p>
                <p className="text-2xl font-bold text-emerald-700 dark:text-emerald-300">{summary.columns}</p>
              </div>
            </div>
          ) : (
            <p className="text-slate-400 text-sm">No summary available. Upload data first.</p>
          )}
        </div>

        {/* Sample Data */}
        <div className="report-anim bg-white dark:bg-slate-800/50 rounded-2xl border border-slate-200 dark:border-slate-700/50 p-5 shadow-sm mb-6">
          <div className="flex items-center gap-2 mb-4">
            <MdTableView className="text-cyan-500" size={20} />
            <h3 className="text-base font-semibold text-slate-800 dark:text-slate-200">Sample Data</h3>
          </div>
          {data.length > 0 ? (
            <div className="overflow-x-auto rounded-xl border border-slate-200 dark:border-slate-700/50">
              <table className="w-full text-sm">
                <thead>
                  <tr className="bg-slate-50 dark:bg-slate-800/50">
                    {Object.keys(data[0]).map((key) => (
                      <th key={key} className="px-4 py-3 text-left text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider border-b border-slate-200 dark:border-slate-700">{key}</th>
                    ))}
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                  {data.slice(0, 5).map((row, i) => (
                    <tr key={i} className="hover:bg-indigo-50/50 dark:hover:bg-slate-800/50 transition-colors">
                      {Object.values(row).map((val, j) => (
                        <td key={j} className="px-4 py-3 text-slate-700 dark:text-slate-300 whitespace-nowrap">{val}</td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <p className="text-slate-400 text-sm">No data found.</p>
          )}
        </div>

        {/* Info notice */}
        <div className="report-anim flex items-start gap-3 p-4 rounded-xl bg-indigo-50 dark:bg-indigo-500/10 border border-indigo-100 dark:border-indigo-500/20 mb-6">
          <MdInfo className="text-indigo-500 mt-0.5 shrink-0" size={18} />
          <p className="text-sm text-indigo-700 dark:text-indigo-300">
            Charts generated on Dashboard & Tools pages will be included in the PDF export.
          </p>
        </div>

        {/* Export buttons */}
        <div className="report-anim flex flex-wrap gap-3">
          <button
            onClick={downloadCSV}
            className="flex items-center gap-2 px-6 py-3 rounded-xl bg-emerald-500 text-white font-medium shadow-lg shadow-emerald-500/20 hover:shadow-xl hover:-translate-y-0.5 active:translate-y-0 transition-all duration-300 cursor-pointer"
          >
            <MdDownload size={18} />
            Download CSV
          </button>
          <button
            onClick={downloadPDF}
            className="flex items-center gap-2 px-6 py-3 rounded-xl bg-red-500 text-white font-medium shadow-lg shadow-red-500/20 hover:shadow-xl hover:-translate-y-0.5 active:translate-y-0 transition-all duration-300 cursor-pointer"
          >
            <MdPictureAsPdf size={18} />
            Download PDF
          </button>
        </div>
      </div>
  );
}
